apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
 containers:
 - name: nginx
   image: nginx
resources:
  requestes:
    memory: "60Mi"
    cpu: "100m"
  limits:
    memory: "120Mi"
    cpu: "200m"
     

