apiVersion: v1
kind: Pod
metadata:
  name: environment-variables
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: COURSE
      value: "k8s"
    - name: TRAINER
      value: "siva"